export const BgImages = [
    '/assets/bgImages/bg-image-1.jpg',
    '/assets/bgImages/bg-image-2.jpg',
    '/assets/bgImages/bg-image-3.jpg',
    '/assets/bgImages/bg-image-4.jpg',
    '/assets/bgImages/bg-image-5.jpg',
    '/assets/bgImages/bg-image-6.jpg',
    '/assets/bgImages/bg-image-7.jpg',
    '/assets/bgImages/bg-image-8.jpg',
    '/assets/bgImages/bg-image-9.jpg',
    // '/assets/bgImages/bg-image-10.png',
    // '/assets/bgImages/bg-image-11.png',
    // '/assets/bgImages/bg-image-12.png',
    // '/assets/bgImages/bg-image-13.png',
    '/assets/bgImages/bg-image-14.jpg',
    '/assets/bgImages/bg-image-15.jpg',
    '/assets/bgImages/bg-image-16.jpg',
    '/assets/bgImages/bg-image-17.jpg',
    '/assets/bgImages/bg-image-18.jpg',
    '/assets/bgImages/bg-image-19.jpg',
    '/assets/bgImages/bg-image-20.jpg',
    '/assets/bgImages/bg-image-21.jpg',
]